# Generated by Django 5.2.4 on 2025-07-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_temporary_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary_link',
            name='expires_after',
            field=models.DurationField(),
        ),
    ]
