# Generated by Django 5.2.4 on 2025-08-02 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_temporary_link_expires_after'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporary_link',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='temporary_link',
            name='expires_after',
        ),
        migrations.AddField(
            model_name='temporary_link',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 16, 32, 1, 866048, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='temporary_link',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 17, 32, 1, 866062, tzinfo=datetime.timezone.utc)),
        ),
    ]
