# Generated by Django 5.2.4 on 2025-12-17 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_temporary_link_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary_link',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 17, 16, 44, 12, 489916, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='temporary_link',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 17, 17, 44, 12, 489933, tzinfo=datetime.timezone.utc)),
        ),
    ]
